### ISSUE TITLE
Need Debian Jessie image

### ISSUE THREAD

**Issue by regit** [pevma/sqard#2]
It is not possible to use Debian Jessie image to build Suricata and it would be convenient.

**Comment by pevma** [comment]
There is one here - https://github.com/pevma/sqard/blob/master/Debian/Dockerfile.sqard-debian-jessie

**Comment by regit** [comment]
Is it available for fetching. I did not see it in the listed tags on dockerhub.

**Comment by pevma** [comment]
Should be fixed now.
Thanks for the pointer!
